// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InApplyFid struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	ExName               string   `protobuf:"bytes,3,opt,name=ExName,proto3" json:"ExName,omitempty"`
	Md5                  string   `protobuf:"bytes,4,opt,name=Md5,proto3" json:"Md5,omitempty"`
	SliceTotal           int32    `protobuf:"varint,5,opt,name=SliceTotal,proto3" json:"SliceTotal,omitempty"`
	ExpiredTime          int64    `protobuf:"varint,6,opt,name=ExpiredTime,proto3" json:"ExpiredTime,omitempty"`
	Width                int32    `protobuf:"varint,7,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               int32    `protobuf:"varint,8,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InApplyFid) Reset()         { *m = InApplyFid{} }
func (m *InApplyFid) String() string { return proto.CompactTextString(m) }
func (*InApplyFid) ProtoMessage()    {}
func (*InApplyFid) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *InApplyFid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InApplyFid.Unmarshal(m, b)
}
func (m *InApplyFid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InApplyFid.Marshal(b, m, deterministic)
}
func (m *InApplyFid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InApplyFid.Merge(m, src)
}
func (m *InApplyFid) XXX_Size() int {
	return xxx_messageInfo_InApplyFid.Size(m)
}
func (m *InApplyFid) XXX_DiscardUnknown() {
	xxx_messageInfo_InApplyFid.DiscardUnknown(m)
}

var xxx_messageInfo_InApplyFid proto.InternalMessageInfo

func (m *InApplyFid) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InApplyFid) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InApplyFid) GetExName() string {
	if m != nil {
		return m.ExName
	}
	return ""
}

func (m *InApplyFid) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *InApplyFid) GetSliceTotal() int32 {
	if m != nil {
		return m.SliceTotal
	}
	return 0
}

func (m *InApplyFid) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *InApplyFid) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *InApplyFid) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type OutApplyFid struct {
	Fid                  int64    `protobuf:"varint,1,opt,name=Fid,proto3" json:"Fid,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutApplyFid) Reset()         { *m = OutApplyFid{} }
func (m *OutApplyFid) String() string { return proto.CompactTextString(m) }
func (*OutApplyFid) ProtoMessage()    {}
func (*OutApplyFid) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *OutApplyFid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutApplyFid.Unmarshal(m, b)
}
func (m *OutApplyFid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutApplyFid.Marshal(b, m, deterministic)
}
func (m *OutApplyFid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutApplyFid.Merge(m, src)
}
func (m *OutApplyFid) XXX_Size() int {
	return xxx_messageInfo_OutApplyFid.Size(m)
}
func (m *OutApplyFid) XXX_DiscardUnknown() {
	xxx_messageInfo_OutApplyFid.DiscardUnknown(m)
}

var xxx_messageInfo_OutApplyFid proto.InternalMessageInfo

func (m *OutApplyFid) GetFid() int64 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *OutApplyFid) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type InUpSliceFileItem struct {
	Fid                  int64    `protobuf:"varint,1,opt,name=Fid,proto3" json:"Fid,omitempty"`
	Part                 int32    `protobuf:"varint,2,opt,name=Part,proto3" json:"Part,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Md5                  string   `protobuf:"bytes,4,opt,name=Md5,proto3" json:"Md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InUpSliceFileItem) Reset()         { *m = InUpSliceFileItem{} }
func (m *InUpSliceFileItem) String() string { return proto.CompactTextString(m) }
func (*InUpSliceFileItem) ProtoMessage()    {}
func (*InUpSliceFileItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *InUpSliceFileItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InUpSliceFileItem.Unmarshal(m, b)
}
func (m *InUpSliceFileItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InUpSliceFileItem.Marshal(b, m, deterministic)
}
func (m *InUpSliceFileItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InUpSliceFileItem.Merge(m, src)
}
func (m *InUpSliceFileItem) XXX_Size() int {
	return xxx_messageInfo_InUpSliceFileItem.Size(m)
}
func (m *InUpSliceFileItem) XXX_DiscardUnknown() {
	xxx_messageInfo_InUpSliceFileItem.DiscardUnknown(m)
}

var xxx_messageInfo_InUpSliceFileItem proto.InternalMessageInfo

func (m *InUpSliceFileItem) GetFid() int64 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *InUpSliceFileItem) GetPart() int32 {
	if m != nil {
		return m.Part
	}
	return 0
}

func (m *InUpSliceFileItem) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InUpSliceFileItem) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func init() {
	proto.RegisterType((*InApplyFid)(nil), "storage.InApplyFid")
	proto.RegisterType((*OutApplyFid)(nil), "storage.OutApplyFid")
	proto.RegisterType((*InUpSliceFileItem)(nil), "storage.InUpSliceFileItem")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0xc9, 0x93, 0x97, 0x3e, 0x4e, 0x3d, 0xd4, 0x45, 0x64, 0x4f, 0x12, 0x72, 0xca, 0xc9,
	0x8b, 0x88, 0x67, 0xc1, 0x06, 0x73, 0xf0, 0x85, 0x4d, 0xc5, 0xa3, 0xac, 0x66, 0x6c, 0x07, 0x36,
	0xcd, 0x92, 0x4e, 0xa1, 0xfa, 0x21, 0xfd, 0x4c, 0xb2, 0x63, 0x90, 0x82, 0xde, 0x7e, 0xff, 0x1f,
	0xfb, 0x67, 0x67, 0x06, 0xe0, 0x8d, 0x1c, 0x9e, 0xf9, 0xa1, 0xe7, 0x5e, 0x4d, 0x36, 0xdc, 0x0f,
	0x76, 0x89, 0xc5, 0x67, 0x04, 0x50, 0xaf, 0xaf, 0xbc, 0x77, 0xef, 0x15, 0xb5, 0x4a, 0x41, 0x72,
	0x67, 0x3b, 0xd4, 0x51, 0x1e, 0x95, 0x07, 0x46, 0x38, 0xb8, 0x86, 0x3e, 0x50, 0xff, 0xcb, 0xa3,
	0x32, 0x36, 0xc2, 0xea, 0x04, 0xb2, 0xf9, 0x4e, 0x5e, 0xc6, 0xf2, 0x72, 0x4c, 0x6a, 0x06, 0xf1,
	0x6d, 0x7b, 0xa1, 0x13, 0x91, 0x01, 0xd5, 0x29, 0x40, 0xe3, 0xe8, 0x15, 0x17, 0x3d, 0x5b, 0xa7,
	0xd3, 0x3c, 0x2a, 0x53, 0xb3, 0x67, 0x54, 0x0e, 0xd3, 0xf9, 0xce, 0xd3, 0x80, 0xed, 0x82, 0x3a,
	0xd4, 0x99, 0x7c, 0xb2, 0xaf, 0xd4, 0x31, 0xa4, 0x4f, 0xd4, 0xf2, 0x4a, 0x4f, 0xa4, 0xfc, 0x1d,
	0xc2, 0x04, 0x37, 0x48, 0xcb, 0x15, 0xeb, 0xff, 0xa2, 0xc7, 0x54, 0x5c, 0xc2, 0xf4, 0x7e, 0xcb,
	0x3f, 0x0b, 0xcd, 0x20, 0xae, 0xa8, 0x95, 0x7d, 0x62, 0x13, 0x30, 0x14, 0x1b, 0xb6, 0xbc, 0xdd,
	0xc8, 0x42, 0xa9, 0x19, 0x53, 0xf1, 0x0c, 0x47, 0xf5, 0xfa, 0xd1, 0xcb, 0x68, 0x15, 0x39, 0xac,
	0x19, 0xbb, 0x3f, 0xea, 0x0a, 0x92, 0x07, 0x3b, 0xf0, 0x58, 0x16, 0x0e, 0xee, 0xda, 0xb2, 0x95,
	0x5b, 0x1c, 0x1a, 0xe1, 0xdf, 0x97, 0x78, 0xc9, 0xe4, 0xf4, 0xe7, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x2a, 0xd5, 0x04, 0x00, 0x88, 0x01, 0x00, 0x00,
}
